config/routes.rb
Rails.application.routes.draw do
  root "comics#index"
  get "/search", to: "comics#show"
  post "favorite_comics/create", to: "favorite_comics#create"
  delete "favorite_comics/destroy", to: "favorite_comics#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite_comic.rb
class FavoriteComic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comics_controller.rb
# frozen_string_literal: true

class ComicsController < ApplicationController
  before_action :set_page_number, only: [:index, :show]
  before_action :get_characters_ids, only: [:show]

  def index
    @comics = ProcessApiResponse::FilterComicsInformation.new(@page).call

    if @comics.nil?
      redirect_back fallback_location: root_path
    else
      favorites_list
    end
  end

  def show
    if @characters_ids.empty?
      flash[:notice] = "Character not found"
      redirect_back fallback_location: root_path
    else
      @comics = ProcessApiResponse::FilterComicsInformation.new(@page, @characters_ids).call

      favorites_list
    end
  end

  private
    def set_page_number
      return @page = params[:page] if params[:page].present? && params[:page].to_i >= 0

      @page = 0
    end

    def get_characters_ids
      @characters_ids ||= ProcessApiResponse::FilterCharactersId.new(params[:character_name]).call
    end

    def favorites_list
      @favorites_list = ProcessApiResponse::FilterFavoriteComics.new(@comics).call
    end
end

app/controllers/favorite_comics_controller.rb
# frozen_string_literal: true

class FavoriteComicsController < ApplicationController
  def create
    @favorite_comic = FavoriteComic.create(marvel_id: params[:marvel_id])

    redirect_back fallback_location: root_path
  end

  def destroy
    @favorite_comic = FavoriteComic.find_by(marvel_id: params[:marvel_id])
    @favorite_comic.destroy

    redirect_back fallback_location: root_path
  end

  private
    def favorite_comic_params
      params.require(:favorite_comic).permit(:marvel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comics/_comics_list.html.erb
<div class="row">
  <% comics.each do |comic| %>
    <div class="col-md-2">
      <% if @favorites_list.include?(comic[:id]) %>
        <div class="favorite"><%= image_tag "heart_on.png" %></div>
        <div class="image" style= "border-color: red; border-style: solid; border-width: 10px;">
            <%= button_to image_tag(comic[:image]), favorite_comics_destroy_path, params: { marvel_id: comic[:id] }, method: :delete %>
        </div>
      <% else %>
        <div class="unfavorite"></div>
        <div class="image">
          <%= button_to image_tag(comic[:image]), favorite_comics_create_path, params: { marvel_id: comic[:id] }, method: :create %>
        </div>
      <% end %>
      <div class="text"><%= comic[:title] %></div>
    </div>
  <% end %>
</div>

app/views/comics/index.html.erb
<div class='container'>
  <%= render 'comics_list', comics: @comics %>
  <div class="row">
    <div class="col-md-12">
      <% if @page.to_i >= 1 %>
        <%= link_to "Previews Page", { page: params[:page].to_i - 1 }, class: 'btn btn-light left' %>
      <% end %>
      <%= link_to "Next Page", { page: params[:page].to_i + 1 }, class: 'btn btn-light right' %></button>
    </div>
  </div>
</div>

app/views/comics/show.html.erb
<div class='container'>
  <%= render 'comics_list', comics: @comics %>
  <div class="row">
    <div class="col-md-12">
      <% if @page.to_i >= 1 %>
        <%= link_to "Previews Page", { page: params[:page].to_i - 1, character_name: params[:character_name] }, class: 'btn btn-light left' %>
      <% end %>
      <%= link_to "Next Page", { page: params[:page].to_i + 1, character_name: params[:character_name] }, class: 'btn btn-light right'%>
    </div>
  </div>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color:#353232;">
    <nav class="navbar fixed-top navbar-light"  style="background-color: #e12315; height: 150px">
      <div class="col-md-4"></div>
      <div class="col-md-7 navbar">
        <div>
          <div style="padding-left: 60px;">
          <%= button_to image_tag("marvel_logo.png"), root_path, size: "100x50"%></div>
          <p style="padding-left: 100px;">
            <%= form_tag("/search", method: "get", id: 'name_search') do %>
              <%= text_field_tag(:character_name, params[:character_name]) %>
            <% end %>
          <p>
          <%= flash[:notice] %> <%= flash[:alert] %> 
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>